### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by livnev** [Ralith/riot-electron-nix#10]
Hi, thanks for making this package. Some basic installation instructions/hints would be very helpful for a young Nix user like me. The naive option of doing `nix-build` etc. doesn't seem to be the right thing, I understand that this needs to be added to `nixpkgs` somehow.

**Comment by kenogo** [comment]
So I got it working (although maybe not the way the dev inteded haha). The first important thing is that you actually need to clone the [vector-im/riot-web](https://github.com/vector-im/riot-web) repo in the location of this repo's `riot-web` directory (so `rm -r riot-web; git clone https://github.com/vector-im/riot-web`). Then you need to `cd node` and run `./generate.sh`.

Then I replaced the function arguments at the top of the `default.nix` file with `with import <nixpkgs> {};` to allow for an easier build command. Then you can just run `nix-build default.nix` to build it. You can install this package by adding it to the `environment.systemPackages` list with `(import /path/to/package)`. More info on that [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/configuration/adding-custom-packages.xml)

**Comment by Ralith** [comment]
`riot-web` is now a submodule, which can be populated/updated by doing `git submodule update --init`. You won't need to run generate.sh unless you've modified the submodule.
