### ISSUE TITLE
riot-web dependency

### ISSUE THREAD

**Issue by pstn** [Ralith/riot-electron-nix#11]
First of all, thanks for the new version!

I tried using it, but nix complained that it couldn't find `node-modules/riot-web` at evaluation time, so I figured I might need to clone the riot-web repository there. I did and checked out v1.0.1 manually. After that my system evaluated and built fine.

I don't necessarily think that this is a bad solution, but maybe adding a line to the docs about it would be a good idea?

**Comment by Ralith** [comment]
Whoops, that was an oversight. For now you can get it working by running `generate.sh` in `node` yourself; I'll try to get it working out of the box again.

**Comment by Ralith** [comment]
Should be fixed by 4ed18d711d565293118987ba618c9a5666c00312.
