### ISSUE TITLE
npm ERR! 404 Not Found: auto-launch@5.0.5

### ISSUE THREAD

**Issue by pstn** [Ralith/riot-electron-nix#9]
I'm having troube building the package since a few versions. I don't quite understand, whats happening, so I attached the [full build log](https://share.xndr.de/iewae5Oheem2oof2aivah7eekeeph4/riotlog)
I don't think that auto-launch itself is faulty, but somehow the packages get extracted to a wrong location(?)
I know next to nothing about npm and have no idea, how to debug this. Can you point me in any direction, what might be wrong on my system?

**Comment by Ralith** [comment]
I think this problem was introduced by an update to npm that occurred some since 18.03. I've previously [reported](https://github.com/svanderburg/node2nix/issues/113) the issue upstream.

**Comment by pstn** [comment]
I can confirm that this is the case. Building the package with the nixos-18.03 channel seems to work.

I think we should leave this issue open until it's fixed upstream to let people know that run into this problem... There might be even more, when nixos-18.09 releases, which should happen in the coming days, I think.

**Comment by Ralith** [comment]
Looks like this and similar issues are due to upstream never updating their lockfile. Workaround implemented in 3a3984c6f96de54d57198fe897bdd6270acb3245.
